user_name = input('What is your name: ')
adj_one = input('Tell me an adjective: ')
input('Press Enter to Continue')
noun_one = input('Tell me a noun (plural): ')
input('Press Enter to Continue')
noun_two = input('Tell me another noun: ')
input('Press Enter to Continue')
adj_two = input('Tell me an another adjective: ')
input('Press Enter to Continue')

print(f'\n{user_name} Poem')
print(f'Roses are  {adj_one}')
print(f'{noun_one} are blue')
print(f'{noun_two}  is a {adj_two}')
print(f'And so are you!')
